### ISSUE TITLE
Unhelpful error handling

### ISSUE THREAD

**Issue by slavco86** [statsig-io/js-client#35]
During recent partial outage of Statsig US and EU servers we have discovered the following issue:
Even though a call to  `/initialize` API is failing, Statsig js-client is still resolving `initializeAsync` promise as success?
Upon looking up the "initialized" SDK class - the `loadingStatus` property is also set to "Ready", which makes it impossible to build any sort of failover logic which would gracefully handle the outage event.
![Screenshot 2024-10-25 at 11 28 45](https://github.com/user-attachments/assets/765b5994-c949-45ad-a36c-9c43f00f7375)

**Comment by dan-loomb** [comment]
Hey @slavco86, this looks to be the [`@statsig/js-client`](https://github.com/statsig-io/js-client-monorepo/blob/main/packages/js-client/package.json) SDK, correct? This repo is for the legacy [`statsig-js`](https://github.com/statsig-io/js-client/blob/main/package.json) SDK.

We intentionally do not reject/throw to avoid breaking customers websites.

If you would like to have a hook for when the initialize network request fails in `@statsig/js-client`, you can subscribe to `initialization_failure`.

```ts
myStatsigClient.on("initialization_failure", (event) => {
  // something went wrong with the network reqeust
});
```

`loadingStatus` is "Ready" as this is consumed by the @statsig/react-bindings package so it can now whether or not startup is completed. We may have cached values from a previous session.

**Comment by slavco86** [comment]
Hi @daniel-statsig ,

Thanks for your prompt response and sorry for mixing up the repos. I have tried your suggestion but unfortunatley it doesn't seem to work.
1. There doesn't seem to be event `"initialization_failure"` to subscribe to defined in statsig client.
2. I tried the `error` event - but it also didn't work when the calls to `/initialize` are failing.

```type EventNameToEventDataMap = {
    values_updated: {
        status: StatsigLoadingStatus;
        values: DataAdapterResult | null;
    };
    session_expired: object;
    error: {
        error: unknown;
    };
    logs_flushed: {
        events: Record<string, unknown>[];
    };
    pre_shutdown: object;
    gate_evaluation: {
        gate: FeatureGate;
    };
    dynamic_config_evaluation: {
        dynamicConfig: DynamicConfig;
    };
    experiment_evaluation: {
        experiment: Experiment;
    };
    layer_evaluation: {
        layer: Layer;
    };
};
````

Do you want me to raise this in the other repo instead or you happy to look into this here?

**Comment by dan-loomb** [comment]
No worries. I think you may need to update your version of the SDK. Here is the event I am referring too: https://github.com/statsig-io/js-client-monorepo/blob/main/packages/client-core/src/StatsigClientEventEmitter.ts#L33

**Comment by slavco86** [comment]
I think we are using the latest version `"@statsig/js-client": "^1.7.0",` which is what we get from running `npm install @statsig/js-client` as per documentation [here](https://docs.statsig.com/client/javascript-sdk/?ref=gh_jsm)
But it still is missing the event you pointed to. 
Am I missing something?

**Comment by dan-loomb** [comment]
Hmm, I think you might have you might have you major version locked to 1.x.x. 

The latest version is 3.3.0 https://www.npmjs.com/package/@statsig/js-client/v/latest

**Comment by slavco86** [comment]
LOL! It's late here.
Thanks for spotting this.
I can confirm your solution works. I can now tap into the initialization failure.

Thanks again for your responses.
I'll close the issue

**Comment by dan-loomb** [comment]
Nice, happy to help. Let me know if you need anything else.
