### ISSUE TITLE
SecurityError on iOS

### ISSUE THREAD

**Issue by mdekker-eb** [statsig-io/js-client#6]
Operating System: iOS 15.3
Browser: Safari

When I enable "Block all Cookies" in the safari settings, when I try to use the statsig SDK, i am getting a unhandled exception:
`SecurityError: The operation is insecure.`
In the console (you can attach to a console using safari on desktop and connecting your phone / simulator)

in utils/StatsigLocalStorage.js:
```
   }
    StatsigLocalStorage.getItem = function (key) {
        if (typeof Storage !== 'undefined' &&
            typeof window !== 'undefined' &&
            window != null &&
This line throwing the exception >>          window.localStorage != null) {
            return window.localStorage.getItem(key);
        }
        else {
            return this.fallbackSessionCache[key];
        }
```

**Comment by tore-statsig** [comment]
We’ve handled the possible exception from [setItem](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem) as documented

But documentation for [getItem](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem) does not show any exceptions.  I suppose browser blocking implementations have added this.  We will update our usage of local storage to handle this.  Thanks for the report!

**Comment by tore-statsig** [comment]
Patched in https://github.com/statsig-io/js-client/releases/tag/v4.14.3
