### ISSUE TITLE
LocalStorage is not checked for

### ISSUE THREAD

**Issue by roscioli** [statsig-io/js-client#7]
Currently we uncovered a bug wherein some browser configurations without local storage support will cause the statsig client to error out. Could we get a simple check that localStorage is available in this library before accessing it?

To reproduce in Chrome, you can turn on "block all cookies"

**Comment by vijaye-statsig** [comment]
Thank you for reporting.  We'll address that asap. cc: @tore-statsig

**Comment by tore-statsig** [comment]
Ah interesting.  We've handled storage being unavailable, but it looks like the way this is implemented in chrome throws even if you are checking if local storage is defined.  We can move the try/catch up to handle this

https://github.com/statsig-io/js-client/blob/main/src/utils/StatsigLocalStorage.ts#L7

**Comment by tore-statsig** [comment]
Ironically - you cant comment on a github issue if you have this setting turned on either.  I wonder how many things break across the web with this.

**Comment by roscioli** [comment]
Yeah, a lot of things do break for sure, but we confirmed that this actually occurs fairly regularly in the wild.

**Comment by tore-statsig** [comment]
And easy enough to fix - published v4.15.3 - thanks for the report!

https://github.com/statsig-io/js-client/releases/tag/v4.15.3

**Comment by roscioli** [comment]
And thank you for the quick turnaround!
